version: "3"
# Version 0.2
# 
services:
  ccu-jack:
    image: ccu-jack:latest
    container_name: ccu-jack
    hostname: ccu-jack
    environment:
      - TZ=Europe/Berlin
    volumes:
      # replace ./wd/ccu-jack.cfg with your own path to config
      - ./ccu-jack.cfg:/go/src/app/ccu-jack.cfg:ro
    #networks:
    #  - web
    security_opt:
      - no-new-privileges:true
    ports:
      # MQTT
      - 1883:1883 
      # MQTT TLS
      - 8883:8883
      # CCU-Jack VEAM/UI
      - 2121:2121
      # CCU-Jack VEAM/UI TLS
      - 2122:2122

    restart: unless-stopped

#networks:
#  web:
#    external: true
